# This is the project Terminal_Clock configuration file.
# Using this file, you can radically change the appearance
# of this terminal utility and create your own custom clock.

# Here you have the ability to change the clock width, freely change colors
# for any object, and also change the characters
# of the objects.



# Width clock
=2

# Main back color
=47

# Main back additional color
=40

# Main front color
=37

# Main front additional color
=30

# Circle back color
=40

# Circle back additional color
=47

# Circle front color
=37

# Circle front additional color
=30

# Symbol for circle
- 

# Number back color
=47

# Number back additional color
=40

# Number front color
=30

# Number front additional color
=37

# Symbol for tick
-.

# Symbol for first hour
-1

# Symbol for second hour
-2

# Symbol for third hour
-3

# Symbol for fourth hour
-4

# Symbol for fifth hour
-5

# Symbol for sixth hour
-6

# Symbol for seventh hour
-7

# Symbol for eighth hour
-8

# Symbol for ninth hour
-9

# Symbol for tenth hour
-10

# Symbol for eleventh hour
-11

# Symbol for twelwth hour
-12

# Second back color
=47

# Second back additional color
=40

# Second front color
=30

# Second front additional color
=37

# Symbol for vertical line second
-|

# Symbol for first diagonal line second
-/

# Symbol for second diagonal line second
-\

# Symbol for horizontal line second
--


# Color palette for custom clock design:

# Colors for the character itself
# 30 - black
# 31 - red
# 32 - green
# 33 - yellow
# 34 - blue
# 35 - purple/magenta
# 36 - cyan
# 37 - white

# Colors for the character background
# 40 - black
# 41 - red
# 42 - green
# 43 - yellow
# 44 - blue
# 45 - purple
# 46 - cyan
# 47 - white

# Bright colors for the character itself
# 90 - black
# 91 - red
# 92 - green
# 93 - yellow
# 94 - blue
# 95 - purple
# 96 - cyan
# 97 - white

# Bright colors for the character background
# 100 - black
# 101 - red
# 102 - green
# 103 - yellow
# 104 - blue
# 105 - purple
# 106 - cyan
# 107 - white

# ! The description is approximate; colors may look different on various terminals.


# If a character is read, there must be a '-' character at the beginning of the line as an indicator
# that it is a character. It is important to note that after this character, a minimum of 1 character
# and a maximum of 2 characters will be read. Almost any characters from 1 to 4 bytes are read.

# If a number is read, there must be an '=' character at the beginning of the line as an indicator
# that it is a number. It is important to note that after this character, a minimum of 1 digit
# and a maximum of 3 digits will be read. Also, after the '=' character, there should be no other characters,
# not even a space, only digits.

